name: "build"
on:
  pull_request:
    branches: ["master"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
    - name: build
      run: nix-build ./stats.nix
